del ..\loadscr\x3screen85130.jpg
del ..\loadscr\x3screen85131.jpg
del ..\loadscr\x3screen85132.jpg
del ..\scripts\al.plugin.Anarkis.PirateGuild.xml
del ..\scripts\al.Anarkis.Pirate.Import.xml
del ..\scripts\al.Anarkis.Pirate.Init.xml
del ..\scripts\al.Anarkis.Pirate.Main.xml
del ..\scripts\al.Anarkis.Pirate.Setup.DeleteBH.xml
del ..\scripts\al.Anarkis.Pirate.Setup.Init.xml
del ..\scripts\al.Anarkis.Pirate.Stop.xml
del ..\scripts\al.Anarkis.Pirate.Tick.xml
del ..\scripts\al.Anarkis.Pirate.Update.Init.xml
del ..\scripts\al.Anarkis.Pirate.Update.Setup.xml
del ..\scripts\al.Anarkis.Pirate.Update.Stop.xml
del ..\scripts\al.Anarkis.Pirate.Update.xml
del ..\scripts\al.plugin.Anarkis.PirateGuild.xml
del ..\scripts\Cmd.Anarkis.Pirate.Attack.xml
del ..\scripts\Cmd.Anarkis.Pirate.AttackLand.xml
del ..\scripts\Cmd.Anarkis.Pirate.Carrier.Hq.AI.xml
del ..\scripts\Cmd.Anarkis.Pirate.DefendBase.xml
del ..\scripts\Cmd.Anarkis.Pirate.Invade.xml
del ..\scripts\Cmd.Anarkis.Pirate.Patrol.Long.xml
del ..\scripts\Cmd.Anarkis.Pirate.Patrol.xml
del ..\scripts\Cmd.Anarkis.Pirate.PBtoPB.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.AttackSame.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Base.AI.Decision.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Base.AI.Name.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Base.AI.Return.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Base.AI.Special.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Base.AI.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.BaseBoss.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Boss.AI.Flee.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Boss.AI.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Dock.Repairs.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Hunter.AI.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Order.BossRequest.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Order.Buy.At.SY.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Order.Defences.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Order.Invade.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Order.KillStation.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Order.Patrol.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Order.RaidRequest.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Order.RaidTS.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Order.TrainPilots.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Order.Weaken.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Protect.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Task.HullCheck.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Task.Mission.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Task.PB.Monitor.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Task.Radar.Boss.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Task.Rem.Signals.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Timer.Return.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Wing.Attack.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Wing.ChangeLeader.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Wing.Cover.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Wing.Invade.xml
del ..\scripts\Lib.Cmd.Anarkis.Pirate.Wing.Patrol.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.ADS.Audio.Alert.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.ADS.Get.GuildOnly.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Bounty.Add.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Build.Boss.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Build.BountyHunt.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Build.Carrier.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Build.Convoy.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Build.Defense.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Build.Destroyer.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Build.Dome.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Build.Frigate.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Build.Ship.At.SY.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Build.Ship.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Build.Shipyard.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Build.Station.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Build.TL.Dome.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Build.TLconvoy.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Check.InDanger.Boss.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Check.InDanger.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Comm.Ship.FindPB.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Comm.Ship.FindSY.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Comm.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Downgrade.Base.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Find.NeedHelp.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Find.PB.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Find.SafePlace.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Find.Sector.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Find.Station.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Find.Target.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Get.ByReward.Fast.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Get.DefenderList.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Get.Fine.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Get.FreeDefenders.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Get.Hunter.List.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Get.Hunters.From.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Get.Prize.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Get.RaidCost.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Get.RandomDocked.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Get.RelValue.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Give.TgtSignal.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Money.Add.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.News.Delete.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.News.Get.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.News.Set.Global.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.News.Set.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Promote.Base.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Promote.Ship.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Rel.Apply.Def.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Rel.Apply.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Rel.Change.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Rename.Military.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Rename.Ship.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Respawn.SY.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Reward.Add.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Rnd.Adv.Class.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Rnd.CorvetteClass.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Rnd.FighterClass.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Rnd.HeavyCorvette.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.SetRelation.PG.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.SetRelation.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Ship.FF.Settings.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Signal.Restore.Tgt.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Station.Restore.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Station.SetFriend.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Trade.AddProducts.xml
del ..\scripts\Lib.Gen.Anarkis.Pirate.Trade.RemProducts.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.Base.Kills.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.Base.SM.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.Base.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.Browse.News.SM.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.Browse.News.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.Game.A.SM.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.Game.A.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.GiveShip.SM.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.GiveShip.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.HackStation.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.Mission.SM.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.Mission.Submenu.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.Mission.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.Pleasure.SM.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.Pleasure.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.RaidRequest.SM.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.RaidRequest.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.Ship.GetNews.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.Ship.SM.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.Ship.Submenu.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.Ship.xml
del ..\scripts\Menu.Anarkis.Pirate.Comm.Special.xml
del ..\scripts\Menu.Anarkis.Pirate.Debug.Locator.SM.xml
del ..\scripts\Menu.Anarkis.Pirate.Debug.Locator.xml
del ..\scripts\Menu.Anarkis.Pirate.ImportDialog.xml
del ..\scripts\Menu.Anarkis.Pirate.Setup.SM.xml
del ..\scripts\Menu.Anarkis.Pirate.Setup.Strength.xml
del ..\scripts\Menu.Anarkis.Pirate.Setup.xml
del ..\scripts\plugin.Anarkis.Pirate.ECS.Register.xml
del ..\scripts\plugin.Anarkis.Pirate.ECS.Remove.xml
del ..\scripts\setup.EI.AnarkisPirate.xml
del ..\scripts\Sig.Anarkis.Pirate.Boss.Attacked.xml
del ..\scripts\Sig.Anarkis.Pirate.Dest.Killed.xml
del ..\scripts\Sig.Anarkis.Pirate.Hq.Attacked.xml
del ..\scripts\Sig.Anarkis.Pirate.Hq.Killed.xml
del ..\scripts\Sig.Anarkis.Pirate.PB.Attacked.xml
del ..\scripts\Sig.Anarkis.Pirate.PB.Killed.xml
del ..\scripts\Sig.Anarkis.Pirate.Pgs.Captured.xml
del ..\scripts\Sig.Anarkis.Pirate.Pgs.Killed.xml
del ..\scripts\Sig.Anarkis.Pirate.Unified.xml
del ..\scripts\Z.EmpireCopy.AnarkisPirate.Export.xml
del ..\scripts\Z.EmpireCopy.AnarkisPirate.Import.xml
del ..\t\8513-L044.xml
